#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Jan 13, 2020 07:19:05 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}



    menu .pop43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop43" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background #b5ea4b \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x294+347+141
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1089 587
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "User details"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men46" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Next doctor's appointment} 
    menu $site_3_0.men46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men46 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command go_to_doc -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) \
        -label {Go to availability of doctors} 
    $site_3_0 add cascade \
        -menu "$site_3_0.men46" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Next doctor's appointment} -menu "$site_3_0.men47" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Billing 
    menu $site_3_0.men47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men47 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command visiting_cost \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Doctor's visiting cost} 
    $site_3_0.men47 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command m_cost -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Medicine cost} 
    $site_3_0.men47 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command test_cost -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Test cost} 
    $site_3_0.men47 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command total_cost \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Total cost} 
    $site_3_0 add cascade \
        -menu "$site_3_0.men46" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Next doctor's appointment} -menu "$site_3_0.men47" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Billing \
        -menu "$site_3_0.men43" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Availability of  Docs} 
    menu $site_3_0.men43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men43 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command cardo -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Cardiology 
    $site_3_0.men43 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command nero -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Neurology 
    $site_3_0.men43 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command ophth -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Ophthalmology 
    $site_3_0.men43 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command gyne -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Gynecology 
    $site_3_0.men43 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command orth -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Orthopedic 
    $site_3_0.men43 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command ent -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {E N T} 
    $site_3_0 add cascade \
        -menu "$site_3_0.men46" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Next doctor's appointment} -menu "$site_3_0.men47" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Billing \
        -menu "$site_3_0.men43" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Availability of  Docs} -menu "$site_3_0.men48" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Previous health report} 
    menu $site_3_0.men48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men48 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command p_details -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Prescription details} 
    $site_3_0.men48 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command treport -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Test report} 
    $site_3_0.men48 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command r_print -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Print 
    $site_3_0 add cascade \
        -menu "$site_3_0.men46" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Next doctor's appointment} -menu "$site_3_0.men47" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Billing \
        -menu "$site_3_0.men43" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Availability of  Docs} -menu "$site_3_0.men48" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Previous health report} \
        -menu "$site_3_0.men49" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label Prescrption 
    menu $site_3_0.men49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men49 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command show -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Show 
    $site_3_0 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {Log out} 
    listbox $top.lis44 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 232 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -width 564 
    .top42.lis44 configure -font "TkFixedFont"
    .top42.lis44 insert end text
    vTcl:DefineAlias "$top.lis44" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.lis44 <<ListboxSelect>> {
        doc_select
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lis44 \
        -in $top -x 20 -y 20 -width 564 -relwidth 0 -height 232 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

