#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 18, 2019 11:48:58 AM IST  platform: Windows NT
#    Dec 19, 2019 06:21:58 PM IST  platform: Windows NT
#    Dec 23, 2019 10:29:42 AM IST  platform: Windows NT
#    Dec 23, 2019 10:32:04 AM IST  platform: Windows NT
#    Dec 23, 2019 10:40:30 AM IST  platform: Windows NT
#    Dec 23, 2019 10:46:09 AM IST  platform: Windows NT
#    Dec 23, 2019 11:01:09 AM IST  platform: Windows NT
#    Dec 23, 2019 11:06:37 AM IST  platform: Windows NT
#    Dec 23, 2019 11:08:25 AM IST  platform: Windows NT
#    Dec 23, 2019 11:14:49 AM IST  platform: Windows NT
#    Dec 23, 2019 11:17:17 AM IST  platform: Windows NT
#    Dec 23, 2019 11:19:25 AM IST  platform: Windows NT
#    Jan 12, 2020 09:55:26 PM IST  platform: Windows NT
#    Feb 10, 2020 12:00:13 PM IST  platform: Windows NT

import sys
import login_support

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

 

try:
    import ttk
    py3 = False

except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def logout():
    root.destroy()
   
    sys.stdout.flush()
   

   

def nero():
    global w
    d_type="neurology"
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(d_type,)
    sqlstat="""SELECT D_ID,D_NAME,AVAILABLE_OF_DATE,AVAILABLE_OF_TIME FROM DOCTOR WHERE D_DEPARTMENT=%s"""
    c.execute(sqlstat,task)
    rows=c.fetchall()
    count=1;
    w.Listbox1.delete(0,'end')
    for row in rows:
        w.Listbox1.insert(count,row)
        #value=listbox.get(listbox.curselection())
        #print(value)
        count+=1
    conn.commit()
    conn.close() 
    sys.stdout.flush()

def cardo():
    global w,uid
    d_type="cardiology"
    import mysql.connector as mysql
    import config_t
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(d_type,)
    sqlstat="""SELECT D_ID,D_NAME,AVAILABLE_OF_DATE,AVAILABLE_OF_TIME FROM DOCTOR WHERE D_DEPARTMENT=%s"""
    c.execute(sqlstat,task)
    rows=c.fetchall()
    count=1;
    w.Listbox1.delete(0,'end')
    for row in rows:
        w.Listbox1.insert(count,row)
        #value=listbox.get(listbox.curselection())
        #print(value)
        count+=1
    conn.commit()
    from config_t import x 
    print("value of x is" + str(x))
    conn.close() 
    sys.stdout.flush()

def r_print():
    print('after_regn_support.r_print')
    sys.stdout.flush()

def ent():
    global w
    d_type="ENT"
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(d_type,)
    sqlstat="""SELECT D_ID,D_NAME,AVAILABLE_OF_DATE,AVAILABLE_OF_TIME FROM DOCTOR WHERE D_DEPARTMENT=%s"""
    c.execute(sqlstat,task)
    rows=c.fetchall()
    count=1;
    w.Listbox1.delete(0,'end')
    for row in rows:
        w.Listbox1.insert(count,row)
        #value=listbox.get(listbox.curselection())
        #print(value)
        count+=1
    conn.commit()
    conn.close() 
    sys.stdout.flush()

def doc_select(evt):
    global w,uid
    import mysql.connector as mysql
    from config_t import x
    uid=x
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    value=w.Listbox1.get(w.Listbox1.curselection())
    #print('after_regn_support.doc_select' + str(value))
    docd=[x for x in value]
    #print(docd)
    #uid=login_support.uid
    docd.append(uid)
    did,dname,ddate,dtime,pid=docd
    task=(pid,ddate,did,dtime)
    sqlstat="""INSERT INTO APPOINTMENT (P_ID,AP_DATE,D_ID,AP_TIME) VALUES(%s,%s,%s,%s)"""
    c.execute(sqlstat,task)
    conn.commit()
    conn.close()
    w.Listbox1.delete(0,'end')
    sys.stdout.flush()

def go_to_doc():
    value=w.Listbox1.get(w.Listbox1.curselection())
    w.uid
    print('after_regn_support.go_to_doc' + value)
    
    sys.stdout.flush()

def gyne():
    global w
    d_type="gynecology"
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(d_type,)
    sqlstat="""SELECT D_ID,D_NAME,AVAILABLE_OF_DATE,AVAILABLE_OF_TIME FROM DOCTOR WHERE D_DEPARTMENT=%s"""
    c.execute(sqlstat,task)
    rows=c.fetchall()
    count=1;
    w.Listbox1.delete(0,'end')
    for row in rows:
        w.Listbox1.insert(count,row)
        #value=listbox.get(listbox.curselection())
        #print(value)
        count+=1
    conn.commit()
    conn.close() 
    sys.stdout.flush()

def m_cost():
    print('after_regn_support.m_cost')
    sys.stdout.flush()

def ophth():
    global w
    d_type="ophthalmology"
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(d_type,)
    sqlstat="""SELECT D_ID,D_NAME,AVAILABLE_OF_DATE,AVAILABLE_OF_TIME FROM DOCTOR WHERE D_DEPARTMENT=%s"""
    c.execute(sqlstat,task)
    rows=c.fetchall()
    count=1;
    w.Listbox1.delete(0,'end')
    for row in rows:
        w.Listbox1.insert(count,row)
        #value=listbox.get(listbox.curselection())
        #print(value)
        count+=1
    conn.commit()
    conn.close() 
    sys.stdout.flush()

def orth():
    global w
    d_type="orthopedic"
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(d_type,)
    sqlstat="""SELECT D_ID,D_NAME,AVAILABLE_OF_DATE,AVAILABLE_OF_TIME FROM DOCTOR WHERE D_DEPARTMENT=%s"""
    c.execute(sqlstat,task)
    rows=c.fetchall()
    count=1;
    w.Listbox1.delete(0,'end')
    for row in rows:
        w.Listbox1.insert(count,row)
        #value=listbox.get(listbox.curselection())
        #print(value)
        count+=1
    conn.commit()
    conn.close() 
    sys.stdout.flush()

def p_details():
    print('after_regn_support.p_details')
    sys.stdout.flush()

 
def show():
    global w,uid
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(uid,)
    sqlstat="""SELECT * FROM PRESCRIPTION WHERE USER_ID=%S"""
    c.execute(sqlstat,task)
    rows=c.fetchall()
    count=1;
    for row in rows:
        w.Listbox1.insert(count,row)
        #value=listbox.get(listbox.curselection())
        #print(value)
        count+=1
    conn.commit()
    conn.close() 
    print('after_regn_support.show')
    sys.stdout.flush()

def test_cost():
    print('after_regn_support.test_cost')
    sys.stdout.flush()

def total_cost():
    print('after_regn_support.total_cost')
    sys.stdout.flush()

def treport():
    import staff_report
    staff_report.vp_start_gui() 
    sys.stdout.flush()

def visiting_cost():
    print('after_regn_support.visiting_cost')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import after_regn
    after_regn.vp_start_gui()





