#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 18, 2019 11:48:58 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def cardio():
    print('after_regn_support.cardio')
    sys.stdout.flush()

def ent():
    print('after_regn_support.ent')
    sys.stdout.flush()

def go_to_doc():
    print('after_regn_support.go_to_doc')
    sys.stdout.flush()

def gyne():
    print('after_regn_support.gyne')
    sys.stdout.flush()

def m_cost():
    print('after_regn_support.m_cost')
    sys.stdout.flush()

def neuro():
    print('after_regn_support.neuro')
    sys.stdout.flush()

def ophth():
    print('after_regn_support.ophth')
    sys.stdout.flush()

def orth():
    print('after_regn_support.orth')
    sys.stdout.flush()

def p_details():
    print('after_regn_support.p_details')
    sys.stdout.flush()

def print():
    print('after_regn_support.print')
    sys.stdout.flush()

def show():
    print('after_regn_support.show')
    sys.stdout.flush()

def test_cost():
    print('after_regn_support.test_cost')
    sys.stdout.flush()

def total_cost():
    print('after_regn_support.total_cost')
    sys.stdout.flush()

def treport():
    print('after_regn_support.treport')
    sys.stdout.flush()

def visiting_cost():
    print('after_regn_support.visiting_cost')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import after_regn
    after_regn.vp_start_gui()




