#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Feb 11, 2020 12:23:41 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def confirm():
    global w,uid
    from config_t import x 
    uid=x
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(uid,)
    sqlstat="""UPDATE APPOINTMENT SET P_CONFIRM=1 WHERE P_ID=%s""" 
    c.execute(sqlstat,task)
    conn.commit()
    d_id=w.did.get()
    task=(d_id,)
    sqlstat="""SELECT NUMBER_OF_PATIENT FROM DOCTOR WHERE D_ID=%s"""
    c.execute(sqlstat,task)
    conn.commit()
    conn.close()
    sys.stdout.flush()
def set_doc_name():
    

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import appointment_confirm
    appointment_confirm.vp_start_gui()





