#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 20, 2019 08:13:03 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def doc_submit(self):
    global w
    id=w.doc_id.get()
    name=w.doc_name.get()
    av_date=w.avl_date.get()
    av_time=w.avl_time.get()
    n_o_p=w.no_of_patient.get()
    on_leave=w.on_leave.get()
    st_time=w.start_time.get()
    e_time=w.end_time.get()
    dept=w.deprt.get()
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    task=(id,name,av_date,av_time,n_o_p,on_leave,st_time,e_time,dept)
    sqlstat="""INSERT INTO DOCTOR(d_id,d_name,available_of_date,available_of_time,number_of_patient,on_leave,start_time,end_time,d_department)values(%s,%s,%s,%s,%s,%s,%s,%s,%s)"""
    c.execute(sqlstat,task)
    conn.commit()
    conn.close()
    
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import doc_entry
    doc_entry.vp_start_gui()





