#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 09, 2019 01:12:03 PM IST  platform: Windows NT

import sys
import after_regn

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
    

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
uid=345
def set_Tk_var():
    global var1
    var1 = tk.StringVar()

def login(self):
    from tkinter import messagebox
    import after_regn
    global w,var1,uid,x
    userid=w.user_id.get()
    uid=userid
    print(uid)
    x=uid
    print("value of x is from login:" + str(x))
    passwd=w.pwd.get()

    usertype=int(var1.get())
    if usertype == 0:
       usertype='normal'
    else:
       usertype='staff'
    import mysql.connector as mysql
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
    c=conn.cursor()
    print(usertype)
    task=(userid,passwd,usertype)
    sqlstat="""SELECT USERNAME FROM HOSPITAL WHERE USERID=%s AND USERPASS=%s AND USERTYPE=%s""" 
    c.execute(sqlstat,task)
    rows=c.fetchall()
    
        
    if len(rows)==1:
        with open("config_t.py","w") as fp:
            fp.write("x=" + str(x))
        after_regn.vp_start_gui()
    else:
        messagebox.showerror("error","incorrect password")
    conn.commit()
    conn.close()
    sys.stdout.flush()

def signin(self):
    from tkinter import messagebox
    global w
    username=w.new_user_name.get()
    phone=w.new_user_ph.get()
    if len(phone)<10 or phone.isdigit()==False:
        messagebox.showwarning("warning","enter a valid phone number")
    else:
        import mysql.connector as mysql
        conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
        c=conn.cursor()
        passwd="passwd123"
        type="normal"
        task=(username,passwd,phone,type)
        sqlstat="""INSERT INTO HOSPITAL(USERNAME,USERPASS,USERPH,USERTYPE)VALUES(%s,%s,%s,%s)"""
        c.execute(sqlstat,task)
        conn.commit()
        sqlstat="""SELECT userid,userpass FROM HOSPITAL WHERE USERNAME=%s AND USERPASS=%s AND USERTYPE=%s"""
        task=(username,passwd,type)
        c.execute(sqlstat,task)
        rows=c.fetchall()
        conn.close()
        for row in rows:
            message="Data is successfully inserted" + str(row[0]) + str(row[1]) 
        messagebox.showinfo("information",message)
        sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import login
    login.vp_start_gui()





