#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 22, 2019 06:43:59 PM IST  platform: Windows NT
#    Dec 22, 2019 06:46:24 PM IST  platform: Windows NT
#    Dec 22, 2019 07:53:38 PM IST  platform: Windows NT
#    Dec 23, 2019 10:07:59 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def t_confirmation():
    import staff_report
    staff_report.vp_start_gui()
    sys.stdout.flush()

def doc_entry():
    import doc_entry
    doc_entry.vp_start_gui()
    sys.stdout.flush()

def avl_of_doc():
    import availablity_of_doc
    availablity_of_doc.vp_start_gui()
    
    sys.stdout.flush()

def report_upload():
    import report_upload
    report_upload.vp_start_gui()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import st_login
    st_login.vp_start_gui()




