#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Feb 10, 2020 09:58:37 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import staff_report_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    staff_report_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    staff_report_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x492+326+66")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.067, rely=0.02, relheight=0.904
                , relwidth=0.867)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Test''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(self.Labelframe1)
        self.Frame1.place(relx=0.058, rely=0.067, relheight=0.551, relwidth=0.894
                , bordermode='ignore')
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.u_id = tk.Entry(self.Frame1)
        self.u_id.place(relx=0.366, rely=0.163,height=20, relwidth=0.374)
        self.u_id.configure(background="white")
        self.u_id.configure(disabledforeground="#a3a3a3")
        self.u_id.configure(font="TkFixedFont")
        self.u_id.configure(foreground="#000000")
        self.u_id.configure(highlightbackground="#d9d9d9")
        self.u_id.configure(highlightcolor="black")
        self.u_id.configure(insertbackground="black")
        self.u_id.configure(selectbackground="#c4c4c4")
        self.u_id.configure(selectforeground="black")

        self.t_name = tk.Entry(self.Frame1)
        self.t_name.place(relx=0.366, rely=0.286,height=20, relwidth=0.374)
        self.t_name.configure(background="white")
        self.t_name.configure(disabledforeground="#a3a3a3")
        self.t_name.configure(font="TkFixedFont")
        self.t_name.configure(foreground="#000000")
        self.t_name.configure(highlightbackground="#d9d9d9")
        self.t_name.configure(highlightcolor="black")
        self.t_name.configure(insertbackground="black")
        self.t_name.configure(selectbackground="#c4c4c4")
        self.t_name.configure(selectforeground="black")

        self.u_date = tk.Entry(self.Frame1)
        self.u_date.place(relx=0.366, rely=0.408,height=20, relwidth=0.374)
        self.u_date.configure(background="white")
        self.u_date.configure(disabledforeground="#a3a3a3")
        self.u_date.configure(font="TkFixedFont")
        self.u_date.configure(foreground="#000000")
        self.u_date.configure(highlightbackground="#d9d9d9")
        self.u_date.configure(highlightcolor="black")
        self.u_date.configure(insertbackground="black")
        self.u_date.configure(selectbackground="#c4c4c4")
        self.u_date.configure(selectforeground="black")

        self.u_time = tk.Entry(self.Frame1)
        self.u_time.place(relx=0.366, rely=0.531,height=20, relwidth=0.374)
        self.u_time.configure(background="white")
        self.u_time.configure(disabledforeground="#a3a3a3")
        self.u_time.configure(font="TkFixedFont")
        self.u_time.configure(foreground="#000000")
        self.u_time.configure(highlightbackground="#d9d9d9")
        self.u_time.configure(highlightcolor="black")
        self.u_time.configure(insertbackground="black")
        self.u_time.configure(selectbackground="#c4c4c4")
        self.u_time.configure(selectforeground="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.323, rely=0.041, height=21, width=164)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Confirmation by user''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.022, rely=0.163, height=26, width=120)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''User id''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.022, rely=0.286, height=26, width=120)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Test name''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.022, rely=0.408, height=21, width=120)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Date''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.022, rely=0.531, height=26, width=120)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Time''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.624, rely=0.816, height=24, width=119)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Confirm payment''')
        self.Button1.bind('<Button-1>',staff_report_support.user_confirmation)

        self.Label9 = tk.Label(self.Frame1)
        self.Label9.place(relx=0.086, rely=0.653, height=21, width=54)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Amount''')

        self.amt = tk.Entry(self.Frame1)
        self.amt.place(relx=0.366, rely=0.653,height=20, relwidth=0.374)
        self.amt.configure(background="white")
        self.amt.configure(disabledforeground="#a3a3a3")
        self.amt.configure(font="TkFixedFont")
        self.amt.configure(foreground="#000000")
        self.amt.configure(highlightbackground="#d9d9d9")
        self.amt.configure(highlightcolor="black")
        self.amt.configure(insertbackground="black")
        self.amt.configure(selectbackground="#c4c4c4")
        self.amt.configure(selectforeground="black")

        self.Frame2 = tk.Frame(self.Labelframe1)
        self.Frame2.place(relx=0.058, rely=0.652, relheight=0.281, relwidth=0.894
                , bordermode='ignore')
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Label6 = tk.Label(self.Frame2)
        self.Label6.place(relx=0.366, rely=0.08, height=21, width=179)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Confirmation by staff''')

        self.Label7 = tk.Label(self.Frame2)
        self.Label7.place(relx=0.086, rely=0.32, height=21, width=103)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Serial number''')

        self.Label8 = tk.Label(self.Frame2)
        self.Label8.place(relx=0.108, rely=0.56, height=21, width=60)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''User id''')

        self.serial_no = tk.Entry(self.Frame2)
        self.serial_no.place(relx=0.366, rely=0.32,height=20, relwidth=0.374)
        self.serial_no.configure(background="white")
        self.serial_no.configure(disabledforeground="#a3a3a3")
        self.serial_no.configure(font="TkFixedFont")
        self.serial_no.configure(foreground="#000000")
        self.serial_no.configure(highlightbackground="#d9d9d9")
        self.serial_no.configure(highlightcolor="black")
        self.serial_no.configure(insertbackground="black")
        self.serial_no.configure(selectbackground="#c4c4c4")
        self.serial_no.configure(selectforeground="black")

        self.user_id = tk.Entry(self.Frame2)
        self.user_id.place(relx=0.366, rely=0.56,height=20, relwidth=0.374)
        self.user_id.configure(background="white")
        self.user_id.configure(disabledforeground="#a3a3a3")
        self.user_id.configure(font="TkFixedFont")
        self.user_id.configure(foreground="#000000")
        self.user_id.configure(highlightbackground="#d9d9d9")
        self.user_id.configure(highlightcolor="black")
        self.user_id.configure(insertbackground="black")
        self.user_id.configure(selectbackground="#c4c4c4")
        self.user_id.configure(selectforeground="black")

        self.Button2 = tk.Button(self.Frame2)
        self.Button2.place(relx=0.817, rely=0.72, height=24, width=75)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Confirm''')
        self.Button2.bind('<Button-1>',staff_report_support.staff_confirmation)

        self.Button3 = tk.Button(self.Frame2)
        self.Button3.place(relx=0.817, rely=0.4, height=24, width=77)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Check''')
        self.Button3.bind('<Button-1>',staff_report_support.check)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="-family {Segoe UI} -size 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





