#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Feb 10, 2020 09:58:39 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}



    menu .pop43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop43" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x492+326+66
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1362 741
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab43 \
        -font TkDefaultFont -foreground black -text Test \
        -background $vTcl(actual_gui_bg) -height 445 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 520 
    vTcl:DefineAlias "$top.lab43" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab43
    frame $site_3_0.fra44 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 245 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 465 
    vTcl:DefineAlias "$site_3_0.fra44" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra44
    entry $site_4_0.ent45 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent45" "u_id" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent46" "t_name" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent47 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent47" "u_date" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent48" "u_time" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Confirmation by user} 
    vTcl:DefineAlias "$site_4_0.lab50" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {User id} 
    vTcl:DefineAlias "$site_4_0.lab51" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Test name} 
    vTcl:DefineAlias "$site_4_0.lab52" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Date } 
    vTcl:DefineAlias "$site_4_0.lab53" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Time 
    vTcl:DefineAlias "$site_4_0.lab54" "Label5" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Confirm payment} 
    vTcl:DefineAlias "$site_4_0.but56" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but56 <Button-1> {
        user_confirmation
    }
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Amount 
    vTcl:DefineAlias "$site_4_0.lab46" "Label9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent49" "amt" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.ent45 \
        -in $site_4_0 -x 170 -y 40 -width 174 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent46 \
        -in $site_4_0 -x 170 -y 70 -width 174 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent47 \
        -in $site_4_0 -x 170 -y 100 -width 174 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent48 \
        -in $site_4_0 -x 170 -y 130 -width 174 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 150 -y 10 -width 164 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 10 -y 40 -width 120 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 10 -y 70 -width 120 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab53 \
        -in $site_4_0 -x 10 -y 100 -width 120 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab54 \
        -in $site_4_0 -x 10 -y 130 -width 120 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but56 \
        -in $site_4_0 -x 290 -y 200 -width 119 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 40 -y 160 -width 54 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent49 \
        -in $site_4_0 -x 170 -y 160 -width 174 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra55 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 125 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 465 
    vTcl:DefineAlias "$site_3_0.fra55" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra55
    label $site_4_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Confirmation by staff} 
    vTcl:DefineAlias "$site_4_0.lab57" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Serial number} 
    vTcl:DefineAlias "$site_4_0.lab58" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {User id} 
    vTcl:DefineAlias "$site_4_0.lab59" "Label8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent62 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent62" "serial_no" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent63" "user_id" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Confirm 
    vTcl:DefineAlias "$site_4_0.but64" "Button2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but64 <Button-1> {
        staff_confirmation
    }
    button $site_4_0.but43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Check 
    vTcl:DefineAlias "$site_4_0.but43" "Button3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but43 <Button-1> {
        check
    }
    place $site_4_0.lab57 \
        -in $site_4_0 -x 170 -y 10 -width 179 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab58 \
        -in $site_4_0 -x 40 -y 40 -width 103 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 50 -y 70 -width 60 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent62 \
        -in $site_4_0 -x 170 -y 40 -width 174 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent63 \
        -in $site_4_0 -x 170 -y 70 -width 174 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but64 \
        -in $site_4_0 -x 380 -y 90 -width 75 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but43 \
        -in $site_4_0 -x 380 -y 50 -width 77 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra44 \
        -in $site_3_0 -x 30 -y 30 -width 465 -relwidth 0 -height 245 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra55 \
        -in $site_3_0 -x 30 -y 290 -width 465 -relwidth 0 -height 125 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m45
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 40 -y 10 -width 520 -relwidth 0 -height 445 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

